# Generated by Django 4.2.5 on 2023-11-17 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0020_feedbacks"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedbacks",
            name="upload",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="student.taskupload",
            ),
            preserve_default=False,
        ),
    ]
